import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <SignedOut>
              <section className="min-h-screen flex items-center justify-center">
                <SignIn />
              </section>
            </SignedOut>
            <SignedIn>
              <div className="w-full min-h-screen">
                <nav className="absolute top-0 right-0 p-4">
                  <UserButton />
                </nav>
                <div className="container">
                  {children}
                </div>
              </div>
            </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}
